### PR TITLE
🎨 Themes

### PR DESCRIPTION
**Pull request by Abourass**
Exposing the CSS variables that you have is really powerful / flexible, but it'd also be nice to be able to use some prebuilt options for some of the more common toast actions. 

Building on that idea, I exposed a `theme` object that has three theme props:
`success` - Green, success style toast theme
`error` - Red, error style toast theme
`warning` - Yellow, warning style toast theme. 

They would be entirely optional but would allow some nice easy and quick composing:
```
import { toast, themes } from '@zerodevx/svelte-toast'

const status = await fetch('sample', {foo: bar})

if (status === 'success'){
  toast.push(message, themes.success)
} else if (status === 'error') {
  toast.push(message, themes.error)
 } else {
  toast.push(message)
 }
```

### CODE REVIEW

**Comment by zerodevx** [comment]
Hi @Abourass - thanks so much for your proposal. Adding a theming (or presets) feature is definitely on the to-do list. I thought to take this opportunity to put this feature out for discussion. 

One of the best features of Svelte is its ability to create beautiful and performant UI in very little lines of code; and with less code, there's less room for bugs. IMO this package really showcases this. :) Much of the heavy lifting (especially animations) is deferred to framework primitives, which results in a super lightweight package with very little bloat.

Following this design objective, I thought to be extra careful on what presets to offer.

Regarding colours (for eg. success, warning and failure), IMO the recommended way is for users to stub it out:

`my-theme.js`:

```js
import { toast } from '@zerodevx/svelte-toast'

export const success = m => toast.push(m, { 
  theme: {
    '--toastBackground': 'green',
    '--toastColor': 'white',
    '--toastProgressBackground': 'darkgreen'
  }
});

export const warning = m => toast.push(m, { theme: { ... } });

export const failure = m => toast.push(m, { theme: { ... } });
```

And just import the stubs in consuming components:

```js
import { success, warning, failure } from './my-theme'

// do something
success('It works!')
...
```

What may be more helpful to users could be presets regarding layout, for example `top-right` (default), `bottom-right`, `bottom-center` etc. The reason being layout changes are typically more complex than colour changes. WDYT?

**Comment by Abourass** [comment]
> Regarding colours (for eg. success, warning and failure), IMO the recommended way is for users to stub it out:

Great idea. May I suggest you add all of the most common (Success, Error, Warning) in this pattern in either the readme or perhaps a wiki page linked from the readme? Working from examples always helps me explore a new library, and serves as a great jumping off point for seeing how they can customize or just create their own. 

> What may be more helpful to users could be presets regarding layout, for example top-right (default), bottom-right, bottom-center etc. The reason being layout changes are typically more complex than colour changes. WDYT?

I've never needed to put toast elsewhere on my sites, but I've certainly been on sites that choose to put it one of the non-default quadrants. Seems like some would find it useful, certainly.

**Comment by zerodevx** [comment]
> May I suggest you add all of the most common (Success, Error, Warning) in this pattern in either the readme or perhaps a wiki page linked from the readme?

Yes, I should (and will) most definitely add this recommendation into the docs. Docs definitely need some work =/

Let's leave this PR open for now - perhaps there'll be other folks who'd like to chime in.

**Comment by zerodevx** [comment]
I'll close this PR for now as it seems creating [stubs](https://github.com/zerodevx/svelte-toast#create-your-own-toast-actions) for themed common toast actions is the de-facto standard. Thanks so much for your time!

**Pull request closed without merging**
