### PR TITLE
auto height

### PR DESCRIPTION
**Pull request by hazg**
Current:
Before
```css
  height: auto;
```
After

### CODE REVIEW

**Comment by zerodevx** [comment]
Hi - the toast height is a CSS variable so by design it's configurable by the user.

The default toast height can be changed globally with:

```html
<style>
:root {
  --toastHeight: auto
}
</style>
```

Or on a per-toast basis with:

```html
<script>
toast.push('Hello world!', {
  theme: {
    '--toastHeight': auto
  }
})
</script>
```

**Comment by hazg** [comment]
Why do you need a hardcoded default value if "auto" works fine?

**Comment by zerodevx** [comment]
Normally having a fixed height is easier to work with especially if you have custom fly-in animations. Also, if height is set to `auto`, short single-line toast messages may look too short. Setting a fixed height while allowing it to be customised with CSS vars is the sensible option IMO.

**Comment by vikbert** [comment]
conflict need to be resolved

**Comment by moalamri** [comment]
@zerodevx I could push a PR for this and use `min-height: 3.5rem` property instead of `height: auto` so the toast can grow, but still has a fixed height so it won't look too small for a single line message.

**Comment by zerodevx** [comment]
Hey, good idea - if you could just change:

https://github.com/zerodevx/svelte-toast/blob/86bc988065967de022e6f3d0ddf01436ac22167a/src/ToastItem.svelte#L25

to:

```css
height: var(--toastHeight,auto); 
min-height: var(--toastMinHeight,3.5rem);
```

then I can probably just merge this in. Thanks!

**Comment by moalamri** [comment]
Alright I will do the PR tomorrow

**Comment by zerodevx** [comment]
Handled by #11

**Pull request closed without merging**
