### PR TITLE
Using component as a message

### PR DESCRIPTION
**Pull request by AlexRevin**
Gives an ability to pass Svelte components as a `msg`.
Compatible with Svelte V3 I suppose.

Also, added `--fix` flag for `eslint` as code is not styled according to rules

- [x] Detect component or string
- [x] Properties to Component
- [x] Documentation update
- [x] Cypress tests

NB! If using with `parcel-plugin-svelte` import should be from `src` like

```
import { SvelteToast, toast } from "@zerodevx/svelte-toast/src";
```

As plugin is stupid enough to understand `svelte` directive in `package.json` and loads `umd` version, which is not getting compiled by parent svelte, thus throwing:

```
Error: 'target' is a required option svelte
```

### CODE REVIEW

**Comment by zerodevx** [comment]
Thanks so much for doing this PR 👍 

So first things first, there's a new minor release that'll land imminently - there are code changes so if you could very kindly rebase your PR based on that... it'll be great! 🙏 

Second, is this a common use-case? I was just wondering what components would be passed in as a message.

Your code looks good in general - I'll add initial comments/thoughts in a moment.

**Review by zerodevx — COMMENTED** [review]
Can you remove these files from commit? `docs/build/` and `package-lock.json`

**Comment by AlexRevin** [comment]
I can't seem to find a branch you mentioned, is it pushed yet?

Removing `package-lock.json` would make the package unstable, as dependencies will not be locked anymore, u sure bout that?

We are using toasts as notifications and various service messages, like cookie consent with the `dismissable: false` for instance. That's why I wanted to have Svelte components within toasts, as there might be buttons to click. Also, because of that I removed the `pointer-events: none` from `SvelteToast.svelte` as it restricts clicking anything but anchors inside the toast.

I have also added the `toastId` property passed to component, as in regards to actions inside, it is now possible to send events to global `toast` dispatcher, which will update the toast.

The simple example is (some pseudocode):
```
main.js

...
toast.push(DummyComponent, {}, { color: '0000FF' })
window.document.body.addEventListener("toast", ({id, color}) => {
  toast.set(id, {}, {color});
});


DummyComponent.svelte

<script>
export let toastId, color;

const setColor = (newColor) => {
  window.document.body.dispatchEvent(
    new CustomEvent("toast", {
      id: toastId,
      color: newColor
    })
}
</script>

<div style={color: color}">
  <button on:click={() => setColor("#CCC")}>grey</button>
  <button on:click={() => setColor("#FF0000")}>red</button>
</div>
```

I am not sure whether this all can be beneficial to original project, however it's cool that the initial source is minimal and simple, so I can leave it inside the fork if it does not play along well with ideas you have

**Comment by AlexRevin** [comment]
f7c511f Also adds the namespaces, so you can have different toasts been displayed at once, but positioned differently
There's an example in docs for that.

We need to show different toasts in different positions, so multiple containers are used for that

**Comment by zerodevx** [comment]
> I can't seem to find a branch you mentioned, is it pushed yet?

Sorry! Can you rebase on top of the latest `v0.4.0` release?

> Removing package-lock.json would make the package unstable, as dependencies will not be locked anymore, u sure bout that?

Don't make any changes to `.gitignore`. Instead, just remove the build files `docs/build/*.*` and `package-lock.json` from this PR. I'll make sure to generate a working `package-lock.json` on my end.

> We are using toasts as notifications and various service messages, like cookie consent with the dismissable: false for instance. That's why I wanted to have Svelte components within toasts, as there might be buttons to click. Also, because of that I removed the pointer-events: none from SvelteToast.svelte as it restricts clicking anything but anchors inside the toast.

Can you selectively allow `pointer-events` only if component-messages is being pushed? Typically for normal messages we disallow `pointer-events` because it blocks main page scrolling and it's usually not needed.

> f7c511f Also adds the namespaces, so you can have different toasts been displayed at once, but positioned differently
There's an example in docs for that.

Thanks! But coincidentally I've already added a [similar feature](https://github.com/zerodevx/svelte-toast#supporting-multiple-toast-containers) in the latest release!

> I am not sure whether this all can be beneficial to original project, however it's cool that the initial source is minimal and simple, so I can leave it inside the fork if it does not play along well with ideas you have

Yes, so one of the design objectives is to keep it simple, so I'm also a little wary about scope creep. However I do see the benefits of supporting component-messages. Let's see how this PR turns out.

**Comment by AlexRevin** [comment]
Hey!

I've merged your branch and removed doubling code from my branch. Have also cleaned it up and left only few pieces:

* Components as a prop
* pointer events var for toastContainer

Have changed the syntax for container as long as you support Objects as the argument for `toast.push`, so it can be done now with:

```
toast.push({
  component: {
    src: DummyComponent, 
    props: {
      foo: 'bar'
    }
  }
})
```

**Comment by zerodevx** [comment]
Hi! Thanks so much for rebasing. This looks clean and concise and good to merge. Thank you for your contribution! 🙏

**Pull request merged**
